// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "ba0f84cf-d53f-4539-ae45-ac837dab12a7");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 1622007414);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1622007341);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1622007314);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1622007384);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1622007372);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1622007246);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 109);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{c8dba2ac-0982-4590-935f-bbd5f70dd87c}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1622007251);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1622007326704");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1622009110704");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1622007256269");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1622028856269");
user_pref("browser.search.region", "PH");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210524215832");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1622007384");
user_pref("browser.startup.homepage_override.buildID", "20210524215832");
user_pref("browser.startup.homepage_override.mstone", "90.0a1");
user_pref("browser.startup.lastColdStartupCheck", 1622007384);
user_pref("browser.tabs.drawInTitlebar", false);
user_pref("browser.toolbars.bookmarks.visibility", "never");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"profiler-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.shortcuts.bookmarks", false);
user_pref("browser.urlbar.shortcuts.history", false);
user_pref("browser.urlbar.shortcuts.tabs", false);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1622007252996");
user_pref("devtools.chrome.enabled", true);
user_pref("devtools.debugger.remote-enabled", true);
user_pref("devtools.everOpened", true);
user_pref("devtools.theme", "dark");
user_pref("devtools.toolsidebar-height.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector", 700);
user_pref("devtools.toolsidebar-width.inspector.splitsidebar", 350);
user_pref("distribution.iniFile.exists.appversion", "90.0a1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "52ad7cdcf445473b9c61daef06cb68d8");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210524215832");
user_pref("extensions.lastAppVersion", "90.0a1");
user_pref("extensions.lastPlatformVersion", "90.0a1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"7f2b4208-d67b-4b2f-bb20-847f5e38fd77\",\"formautofill@mozilla.org\":\"33e9ed14-3f62-462f-85ac-aa6d3e7a383a\",\"pictureinpicture@mozilla.org\":\"3cb621a0-b846-41b1-b0fb-1b60ba7cbba0\",\"screenshots@mozilla.org\":\"a7580c83-0a1b-4640-9836-966c49a8c378\",\"webcompat-reporter@mozilla.org\":\"6440b27e-5b8e-4858-a354-d1836792bfbc\",\"webcompat@mozilla.org\":\"21cbcf87-ad76-4e75-9e41-dded4afdbedc\",\"default-theme@mozilla.org\":\"338af1ec-9a89-4bb3-a7c7-59b78bfa20f5\",\"google@search.mozilla.org\":\"a47518f9-37d5-460e-9f1e-b3d96d15c49e\",\"amazondotcom@search.mozilla.org\":\"e5e7c37d-5909-48f7-bceb-68cba6843799\",\"wikipedia@search.mozilla.org\":\"06d8eb1f-51e6-426e-aa65-37f084ae5404\",\"bing@search.mozilla.org\":\"2b1aa962-cb5c-4633-8a76-f8aba3b0606a\",\"ddg@search.mozilla.org\":\"7b746de3-c1e8-4d29-b8e9-2af831362d80\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1622007252);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgradeDialog-defaultEnabled\",\"enabled\":true,\"targeting\":\"true\",\"variables\":{},\"description\":\"Turn on upgradeDialog by default for all users\"}");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "47964bfa-63bc-4dba-a229-87116740e318");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("toolkit.startup.last_success", 1622007382);
user_pref("toolkit.telemetry.cachedClientID", "6da0348e-74fd-4247-bd23-716bc8b92a69");
user_pref("toolkit.telemetry.previousBuildID", "20210524215832");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
